### ISSUE TITLE
Routes not included

### ISSUE THREAD

**Issue by tholmes59** [learn-co-curriculum/strong-params-basics#13]
The lab was created without routes. I added resources :posts to make the example work to be able to follow along.

**Comment by pamccombs** [comment]
You should either add the requirement to add routes or add it in with the lesson.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
