### ISSUE TITLE
Two Errors not Covered in ReadMe Instructions

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/strong-params-basics#14]
In PostsController the update method should be as follows: 
```
def update
    @post = Post.find(params[:id])
    @post.update(params.require(:post).permit(:title, :description))
    redirect_to post_path(@post)
  end
```
You also are required to create a new migration to add post status. This was also not covered in the ReadMe. 

It would be helpful if these tasks were completed in the ReadMe, or at least mentioned as work that is left to do. I keep thinking that I've incorrectly completed the directions in the ReadMe.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
