### ISSUE TITLE
Be more specific with the page inspector

### ISSUE THREAD

**Issue by Enemy-Stand** [learn-co-curriculum/strong-params-basics#20]
Old: Find the input for title. it should look like this: `<input type="text" value="asdferwer" name="post[title]" id="post_title">`
Suggested new:  Find the input for title. it should look like this: `<input type="text" value="asdferwer" name="post[title]" id="post_title">`(attributes might not be in same order)

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
