### ISSUE TITLE
post_params method incorrect?

### ISSUE THREAD

**Issue by KhalilC** [learn-co-curriculum/strong-params-basics#7]
The post_params method allows both the title and description to be updated, but per the lab the update method is only supposed to allow the title to be updated.  If only the title is allowed to be updated, I think think post_params should be:
```ruby
def post_params(*args)
  params.require(:post).permit(*args)
 end
```
with the permitted fields being passed in as arguments.  (ie updated method below)
```ruby
def update
  @post = Post.find(params[:id])
  @post.update(post_params(:title))
  redirect_to post_path(@post)
end
```

```ruby
def create
  @post = Post.new(post_params(:title, :description))
  @post.save
  redirect_to post_path(@post)
end
```

**Comment by jakeekaj** [comment]
I also noticed this and was about to open an issue. @KhalilC is correct and his version looks good too.
